accounts:
  - name: alice
    coins: ["2000000000000stake","1000000000000000denom1","1000000000000000denom2"]
  - name: bob 
    coins: ["2000000000000stake","1000000000000000denom1"]
  - name: steve
    coins: ["1000000000000000denom2"]
validator:
  name: alice
  staked: "1000000000000stake"
client:
  openapi:
    path: "client/docs/static/openapi.yml"
faucet:
  name: alice
  coins: ["100000stake", "1000000denom1", "1000000denom2"]
build:
  binary: "fundraisingd"
  ldflags: ["-X github.com/tendermint/fundraising/x/fundraising/keeper.enableAddAllowedBidder=true"]