// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fundraising/fundraising.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AuctionType enumerates the valid types of an auction.
type AuctionType int32

const (
	// AUCTION_TYPE_UNSPECIFIED defines the default auction type
	AuctionTypeNil AuctionType = 0
	// AUCTION_TYPE_FIXED_PRICE defines the fixed price auction type
	AuctionTypeFixedPrice AuctionType = 1
	// AUCTION_TYPE_ENGLISH defines the english auction type
	AuctionTypeEnglish AuctionType = 2
)

var AuctionType_name = map[int32]string{
	0: "AUCTION_TYPE_UNSPECIFIED",
	1: "AUCTION_TYPE_FIXED_PRICE",
	2: "AUCTION_TYPE_ENGLISH",
}

var AuctionType_value = map[string]int32{
	"AUCTION_TYPE_UNSPECIFIED": 0,
	"AUCTION_TYPE_FIXED_PRICE": 1,
	"AUCTION_TYPE_ENGLISH":     2,
}

func (x AuctionType) String() string {
	return proto.EnumName(AuctionType_name, int32(x))
}

func (AuctionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{0}
}

// AuctionStatus enumerates the valid status of an auction.
type AuctionStatus int32

const (
	// AUCTION_STATUS_UNSPECIFIED defines the default auction status
	AuctionStatusNil AuctionStatus = 0
	// AUCTION_STATUS_STANDBY defines the standby auction status
	AuctionStatusStandBy AuctionStatus = 1
	// AUCTION_STATUS_STARTED defines the started auction status
	AuctionStatusStarted AuctionStatus = 2
	// AUCTION_STATUS_VESTING defines the vesting auction status
	AuctionStatusVesting AuctionStatus = 3
	// AUCTION_STATUS_DISTRIBUTED defines the distributing auction status
	AuctionStatusDistributing AuctionStatus = 4
	// AUCTION_STATUS_FINISHED defines the finished auction status
	AuctionStatusFinished AuctionStatus = 5
	// AUCTION_STATUS_CANCELLED defines the cancelled auction status
	AuctionStatusCancelled AuctionStatus = 6
)

var AuctionStatus_name = map[int32]string{
	0: "AUCTION_STATUS_UNSPECIFIED",
	1: "AUCTION_STATUS_STANDBY",
	2: "AUCTION_STATUS_STARTED",
	3: "AUCTION_STATUS_VESTING",
	4: "AUCTION_STATUS_DISTRIBUTED",
	5: "AUCTION_STATUS_FINISHED",
	6: "AUCTION_STATUS_CANCELLED",
}

var AuctionStatus_value = map[string]int32{
	"AUCTION_STATUS_UNSPECIFIED": 0,
	"AUCTION_STATUS_STANDBY":     1,
	"AUCTION_STATUS_STARTED":     2,
	"AUCTION_STATUS_VESTING":     3,
	"AUCTION_STATUS_DISTRIBUTED": 4,
	"AUCTION_STATUS_FINISHED":    5,
	"AUCTION_STATUS_CANCELLED":   6,
}

func (x AuctionStatus) String() string {
	return proto.EnumName(AuctionStatus_name, int32(x))
}

func (AuctionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{1}
}

// AddressType enumerates the available types of a address.
type AddressType int32

const (
	// the 32 bytes length address type of ADR 028.
	AddressType32Bytes AddressType = 0
	// the default 20 bytes length address type.
	AddressType20Bytes AddressType = 1
)

var AddressType_name = map[int32]string{
	0: "ADDRESS_TYPE_32_BYTES",
	1: "ADDRESS_TYPE_20_BYTES",
}

var AddressType_value = map[string]int32{
	"ADDRESS_TYPE_32_BYTES": 0,
	"ADDRESS_TYPE_20_BYTES": 1,
}

func (x AddressType) String() string {
	return proto.EnumName(AddressType_name, int32(x))
}

func (AddressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{2}
}

// Params defines the set of params for the fundraising module.
type Params struct {
	// auction_creation_fee specifies the fee for fundraisin creation fee.
	// this prevents from spamming attack and it is collected in the community
	// pool
	AuctionCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=auction_creation_fee,json=auctionCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"auction_creation_fee"`
	// extended_period specifies the extended period that determines how long
	// the extended auction round lasts.
	ExtendedPeriod uint32 `protobuf:"varint,2,opt,name=extended_period,json=extendedPeriod,proto3" json:"extended_period,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuctionCreationFee() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.AuctionCreationFee
	}
	return nil
}

func (m *Params) GetExtendedPeriod() uint32 {
	if m != nil {
		return m.ExtendedPeriod
	}
	return 0
}

// BaseAuction defines a base auction type. It contains all the necessary fields
// for basic auction functionality. Any custom auction type should extend this
// type for additional functionality (e.g. english auction, fixed price
// auction).
type BaseAuction struct {
	// id specifies index of the auction
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type specifies the auction type; type 1 is fixed price and 2 is english
	Type AuctionType `protobuf:"varint,2,opt,name=type,proto3,enum=tendermint.fundraising.AuctionType" json:"type,omitempty"`
	// auctioneer specifies the bech32-encoded address that creates the auction
	Auctioneer string `protobuf:"bytes,3,opt,name=auctioneer,proto3" json:"auctioneer,omitempty"`
	// selling_pool_address specifies the bech32-encoded address that has all the
	// selling coin
	SellingPoolAddress string `protobuf:"bytes,4,opt,name=selling_pool_address,json=sellingPoolAddress,proto3" json:"selling_pool_address,omitempty"`
	// paying_pool_address specifies the bech32-encoded address that has all the
	// paying coin
	PayingPoolAddress string `protobuf:"bytes,5,opt,name=paying_pool_address,json=payingPoolAddress,proto3" json:"paying_pool_address,omitempty"`
	// start_price specifies the starting price of the auction
	StartPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=start_price,json=startPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"start_price"`
	// selling_coin specifies the selling coin for the auction
	SellingCoin types.Coin `protobuf:"bytes,7,opt,name=selling_coin,json=sellingCoin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"selling_coin"`
	// paying_coin_denom specifies the paying coin denom that bidders use to bid
	// for
	PayingCoinDenom string `protobuf:"bytes,8,opt,name=paying_coin_denom,json=payingCoinDenom,proto3" json:"paying_coin_denom,omitempty"`
	// vesting_address specifies the bech32-encoded vesting address that holds
	// vesting amounts of coin
	VestingAddress string `protobuf:"bytes,9,opt,name=vesting_address,json=vestingAddress,proto3" json:"vesting_address,omitempty"`
	// vesting_schedules specifies the vesting schedules for the auction
	VestingSchedules []VestingSchedule `protobuf:"bytes,10,rep,name=vesting_schedules,json=vestingSchedules,proto3" json:"vesting_schedules"`
	// winning_price specifies the winning price of the auction
	WinningPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,11,opt,name=winning_price,json=winningPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"winning_price"`
	// remaining_coin specifes the remaining amount of selling coin to sell
	RemainingCoin types.Coin `protobuf:"bytes,12,opt,name=remaining_coin,json=remainingCoin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"remaining_coin"`
	// start_time specifies the start time of the plan
	StartTime time.Time `protobuf:"bytes,13,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	// end_times specifies the end time of the plan
	EndTimes []time.Time `protobuf:"bytes,14,rep,name=end_times,json=endTimes,proto3,stdtime" json:"end_times"`
	// status specifies the auction status
	Status AuctionStatus `protobuf:"varint,15,opt,name=status,proto3,enum=tendermint.fundraising.AuctionStatus" json:"status,omitempty"`
}

func (m *BaseAuction) Reset()         { *m = BaseAuction{} }
func (m *BaseAuction) String() string { return proto.CompactTextString(m) }
func (*BaseAuction) ProtoMessage()    {}
func (*BaseAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{1}
}
func (m *BaseAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAuction.Merge(m, src)
}
func (m *BaseAuction) XXX_Size() int {
	return m.Size()
}
func (m *BaseAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAuction.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAuction proto.InternalMessageInfo

// FixedPriceAuction defines the fixed price auction type. It is the most
// simpliest way to raise funds. An auctioneer sets the starting price for each
// selling amounts of coin and bidders bid to purchase based on the fixed price.
type FixedPriceAuction struct {
	*BaseAuction `protobuf:"bytes,1,opt,name=base_auction,json=baseAuction,proto3,embedded=base_auction" json:"base_auction,omitempty"`
}

func (m *FixedPriceAuction) Reset()         { *m = FixedPriceAuction{} }
func (m *FixedPriceAuction) String() string { return proto.CompactTextString(m) }
func (*FixedPriceAuction) ProtoMessage()    {}
func (*FixedPriceAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{2}
}
func (m *FixedPriceAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FixedPriceAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FixedPriceAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FixedPriceAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedPriceAuction.Merge(m, src)
}
func (m *FixedPriceAuction) XXX_Size() int {
	return m.Size()
}
func (m *FixedPriceAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedPriceAuction.DiscardUnknown(m)
}

var xxx_messageInfo_FixedPriceAuction proto.InternalMessageInfo

// EnglishAuction defines the english auction type. It is an ascending dynamic
// auction that an auctioneer decides the starting price of the selling amount
// of coin and bidders bid to purchase the amounts of coin. It creates
// competition for the price, not how fast bidders can bid.
type EnglishAuction struct {
	*BaseAuction `protobuf:"bytes,1,opt,name=base_auction,json=baseAuction,proto3,embedded=base_auction" json:"base_auction,omitempty"`
	// maximum_bid_price specifies the maximum bid price for the auction
	MaximumBidPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=maximum_bid_price,json=maximumBidPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"maximum_bid_price"`
	// extended specifies a number of extended rounds
	Extended uint32 `protobuf:"varint,3,opt,name=extended,proto3" json:"extended,omitempty"`
	// extend_rate specifies the rate that decides if the auction needs another
	// round
	ExtendRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=extend_rate,json=extendRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"extend_rate"`
}

func (m *EnglishAuction) Reset()         { *m = EnglishAuction{} }
func (m *EnglishAuction) String() string { return proto.CompactTextString(m) }
func (*EnglishAuction) ProtoMessage()    {}
func (*EnglishAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{3}
}
func (m *EnglishAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnglishAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnglishAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnglishAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnglishAuction.Merge(m, src)
}
func (m *EnglishAuction) XXX_Size() int {
	return m.Size()
}
func (m *EnglishAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_EnglishAuction.DiscardUnknown(m)
}

var xxx_messageInfo_EnglishAuction proto.InternalMessageInfo

// VestingSchedule defines the vesting schedule for the owner of an auction.
type VestingSchedule struct {
	// release_time specifies the time for distribution of the vesting coin
	ReleaseTime time.Time `protobuf:"bytes,1,opt,name=release_time,json=releaseTime,proto3,stdtime" json:"release_time"`
	// weight specifies the vesting weight for the schedule
	Weight github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=weight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"weight"`
}

func (m *VestingSchedule) Reset()         { *m = VestingSchedule{} }
func (m *VestingSchedule) String() string { return proto.CompactTextString(m) }
func (*VestingSchedule) ProtoMessage()    {}
func (*VestingSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{4}
}
func (m *VestingSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingSchedule.Merge(m, src)
}
func (m *VestingSchedule) XXX_Size() int {
	return m.Size()
}
func (m *VestingSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_VestingSchedule proto.InternalMessageInfo

func (m *VestingSchedule) GetReleaseTime() time.Time {
	if m != nil {
		return m.ReleaseTime
	}
	return time.Time{}
}

// VestingQueues defines a repeated set of vesting queues.
type VestingQueues struct {
	Queues []VestingQueue `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues"`
}

func (m *VestingQueues) Reset()      { *m = VestingQueues{} }
func (*VestingQueues) ProtoMessage() {}
func (*VestingQueues) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{5}
}
func (m *VestingQueues) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingQueues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingQueues.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingQueues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingQueues.Merge(m, src)
}
func (m *VestingQueues) XXX_Size() int {
	return m.Size()
}
func (m *VestingQueues) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingQueues.DiscardUnknown(m)
}

var xxx_messageInfo_VestingQueues proto.InternalMessageInfo

func (m *VestingQueues) GetQueues() []VestingQueue {
	if m != nil {
		return m.Queues
	}
	return nil
}

// VestingQueue defines the vesting queue.
type VestingQueue struct {
	// auction_id specifes the id of the auction
	AuctionId uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	// auctioneer specifies the bech32-encoded address that creates the auction
	Auctioneer string `protobuf:"bytes,2,opt,name=auctioneer,proto3" json:"auctioneer,omitempty"`
	// paying_coin specifies the paying amount of coin
	PayingCoin types.Coin `protobuf:"bytes,3,opt,name=paying_coin,json=payingCoin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"paying_coin"`
	// release_time specifies the timestamp of the vesting schedule
	ReleaseTime time.Time `protobuf:"bytes,4,opt,name=release_time,json=releaseTime,proto3,stdtime" json:"release_time"`
}

func (m *VestingQueue) Reset()         { *m = VestingQueue{} }
func (m *VestingQueue) String() string { return proto.CompactTextString(m) }
func (*VestingQueue) ProtoMessage()    {}
func (*VestingQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{6}
}
func (m *VestingQueue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingQueue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingQueue.Merge(m, src)
}
func (m *VestingQueue) XXX_Size() int {
	return m.Size()
}
func (m *VestingQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingQueue.DiscardUnknown(m)
}

var xxx_messageInfo_VestingQueue proto.InternalMessageInfo

func (m *VestingQueue) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *VestingQueue) GetAuctioneer() string {
	if m != nil {
		return m.Auctioneer
	}
	return ""
}

func (m *VestingQueue) GetPayingCoin() types.Coin {
	if m != nil {
		return m.PayingCoin
	}
	return types.Coin{}
}

func (m *VestingQueue) GetReleaseTime() time.Time {
	if m != nil {
		return m.ReleaseTime
	}
	return time.Time{}
}

// Bid defines a standard bid for an auction.
type Bid struct {
	// auction_id specifies the id of the auction
	AuctionId uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	// sequence specifies a number to track first come first served based auction
	// type
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// bidder specifies the bech32-encoded address that bids for the auction
	Bidder string `protobuf:"bytes,3,opt,name=bidder,proto3" json:"bidder,omitempty"`
	// price specifies the increasing bid price is only possible
	Price github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price"`
	// coin specifies the paying amount of coin that the bidder bids
	Coin types.Coin `protobuf:"bytes,5,opt,name=coin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin"`
	// height specifies the block height of the bid
	Height uint64 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	// eligible specifies the bid that is eligible to purchase the selling coin
	Eligible bool `protobuf:"varint,7,opt,name=eligible,proto3" json:"eligible,omitempty"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97a388085f27061, []int{7}
}
func (m *Bid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return m.Size()
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *Bid) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Bid) GetBidder() string {
	if m != nil {
		return m.Bidder
	}
	return ""
}

func (m *Bid) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

func (m *Bid) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Bid) GetEligible() bool {
	if m != nil {
		return m.Eligible
	}
	return false
}

func init() {
	proto.RegisterEnum("tendermint.fundraising.AuctionType", AuctionType_name, AuctionType_value)
	proto.RegisterEnum("tendermint.fundraising.AuctionStatus", AuctionStatus_name, AuctionStatus_value)
	proto.RegisterEnum("tendermint.fundraising.AddressType", AddressType_name, AddressType_value)
	proto.RegisterType((*Params)(nil), "tendermint.fundraising.Params")
	proto.RegisterType((*BaseAuction)(nil), "tendermint.fundraising.BaseAuction")
	proto.RegisterType((*FixedPriceAuction)(nil), "tendermint.fundraising.FixedPriceAuction")
	proto.RegisterType((*EnglishAuction)(nil), "tendermint.fundraising.EnglishAuction")
	proto.RegisterType((*VestingSchedule)(nil), "tendermint.fundraising.VestingSchedule")
	proto.RegisterType((*VestingQueues)(nil), "tendermint.fundraising.VestingQueues")
	proto.RegisterType((*VestingQueue)(nil), "tendermint.fundraising.VestingQueue")
	proto.RegisterType((*Bid)(nil), "tendermint.fundraising.Bid")
}

func init() { proto.RegisterFile("fundraising/fundraising.proto", fileDescriptor_a97a388085f27061) }

var fileDescriptor_a97a388085f27061 = []byte{
	// 1335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4f, 0x6f, 0x13, 0x47,
	0x14, 0xf7, 0x3a, 0x8e, 0x71, 0xc6, 0x89, 0x63, 0xa6, 0x21, 0xdd, 0xac, 0x84, 0xbd, 0x72, 0xff,
	0x10, 0x21, 0xb1, 0x0e, 0x81, 0x96, 0x0a, 0x89, 0x83, 0xd7, 0xbb, 0x86, 0x95, 0x22, 0xe3, 0xee,
	0x3a, 0xa8, 0x20, 0xb5, 0xab, 0xb5, 0x77, 0x70, 0x46, 0xac, 0x77, 0xcd, 0xce, 0x1a, 0x92, 0x43,
	0xa5, 0x4a, 0xbd, 0x20, 0x9f, 0x38, 0xf6, 0xe2, 0x0a, 0xb5, 0xb7, 0x4a, 0x95, 0xaa, 0xaa, 0xa7,
	0x7e, 0x02, 0x8e, 0xa8, 0xa7, 0xaa, 0xaa, 0xa0, 0x82, 0x4b, 0xd5, 0x4f, 0x51, 0xcd, 0xec, 0xd8,
	0x59, 0x27, 0xa1, 0x40, 0x44, 0x4f, 0x9e, 0xf7, 0xe6, 0xfd, 0xde, 0x9b, 0xf9, 0xbd, 0x3f, 0xb3,
	0x06, 0xa7, 0x6f, 0x0f, 0x7d, 0x37, 0x74, 0x30, 0xc1, 0x7e, 0xaf, 0x9a, 0x58, 0x2b, 0x83, 0x30,
	0x88, 0x02, 0xb8, 0x1a, 0x21, 0xdf, 0x45, 0x61, 0x1f, 0xfb, 0x91, 0x92, 0xd8, 0x95, 0x4a, 0xdd,
	0x80, 0xf4, 0x03, 0x52, 0xed, 0x38, 0x04, 0x55, 0xef, 0x9d, 0xef, 0xa0, 0xc8, 0x39, 0x5f, 0xed,
	0x06, 0xd8, 0x8f, 0x71, 0xd2, 0x5a, 0xbc, 0x6f, 0x33, 0xa9, 0x1a, 0x0b, 0x7c, 0x6b, 0xa5, 0x17,
	0xf4, 0x82, 0x58, 0x4f, 0x57, 0x5c, 0x5b, 0xee, 0x05, 0x41, 0xcf, 0x43, 0x55, 0x26, 0x75, 0x86,
	0xb7, 0xab, 0x11, 0xee, 0x23, 0x12, 0x39, 0xfd, 0x41, 0x6c, 0x50, 0xf9, 0x55, 0x00, 0xd9, 0x96,
	0x13, 0x3a, 0x7d, 0x02, 0xbf, 0x04, 0x2b, 0xce, 0xb0, 0x1b, 0xe1, 0xc0, 0xb7, 0xbb, 0x21, 0x72,
	0xd8, 0xe2, 0x36, 0x42, 0xa2, 0x20, 0xcf, 0xad, 0xe7, 0x37, 0xd7, 0x14, 0x1e, 0x8e, 0x9e, 0x4d,
	0xe1, 0x67, 0x53, 0xea, 0x01, 0xf6, 0xd5, 0x8d, 0xc7, 0x4f, 0xcb, 0xa9, 0x1f, 0x9e, 0x95, 0xd7,
	0x7b, 0x38, 0xda, 0x19, 0x76, 0x94, 0x6e, 0xd0, 0xe7, 0x67, 0xe3, 0x3f, 0xe7, 0x88, 0x7b, 0xa7,
	0x1a, 0xed, 0x0d, 0x10, 0x61, 0x00, 0x62, 0x42, 0x1e, 0xa8, 0xce, 0xe3, 0x34, 0x10, 0x82, 0x67,
	0xc0, 0x32, 0xda, 0x65, 0xbc, 0xb8, 0xf6, 0x00, 0x85, 0x38, 0x70, 0xc5, 0xb4, 0x2c, 0xac, 0x2f,
	0x99, 0x85, 0x89, 0xba, 0xc5, 0xb4, 0x97, 0x73, 0xdf, 0x3c, 0x2a, 0xa7, 0xfe, 0x7e, 0x54, 0x16,
	0x2a, 0xff, 0x9c, 0x00, 0x79, 0xd5, 0x21, 0xa8, 0x16, 0x7b, 0x83, 0x05, 0x90, 0xc6, 0xae, 0x28,
	0xc8, 0xc2, 0x7a, 0xc6, 0x4c, 0x63, 0x17, 0x5e, 0x02, 0x19, 0x1a, 0x95, 0xf9, 0x29, 0x6c, 0xbe,
	0xa7, 0x1c, 0xcd, 0xba, 0xc2, 0xe1, 0xed, 0xbd, 0x01, 0x32, 0x19, 0x00, 0x96, 0x00, 0xe0, 0x27,
	0x44, 0x28, 0x14, 0xe7, 0x64, 0x61, 0x7d, 0xc1, 0x4c, 0x68, 0xe0, 0x06, 0x58, 0x21, 0xc8, 0xf3,
	0xb0, 0xdf, 0xb3, 0x07, 0x41, 0xe0, 0xd9, 0x8e, 0xeb, 0x86, 0x88, 0x10, 0x31, 0xc3, 0x2c, 0x21,
	0xdf, 0x6b, 0x05, 0x81, 0x57, 0x8b, 0x77, 0xa0, 0x02, 0xde, 0x19, 0x38, 0x7b, 0x87, 0x00, 0xf3,
	0x0c, 0x70, 0x32, 0xde, 0x4a, 0xda, 0x5f, 0x07, 0x79, 0x12, 0x39, 0x61, 0x64, 0x0f, 0x42, 0xdc,
	0x45, 0x62, 0x96, 0xda, 0xa9, 0x0a, 0x25, 0xfa, 0x8f, 0xa7, 0xe5, 0x0f, 0x5f, 0x83, 0x68, 0x0d,
	0x75, 0x4d, 0xc0, 0x5c, 0xb4, 0xa8, 0x07, 0xd8, 0x07, 0x8b, 0x93, 0x23, 0xd3, 0x82, 0x12, 0x4f,
	0xc8, 0xc2, 0x7f, 0x67, 0xb5, 0xca, 0xb3, 0x7a, 0xe6, 0x35, 0xb3, 0x6a, 0xe6, 0xb9, 0x7f, 0x2a,
	0xc0, 0xb3, 0x80, 0x5f, 0x8a, 0x45, 0xb3, 0x5d, 0xe4, 0x07, 0x7d, 0x31, 0xc7, 0x6e, 0xbb, 0x1c,
	0x6f, 0x50, 0x33, 0x8d, 0xaa, 0x69, 0xe6, 0xef, 0x21, 0x12, 0x51, 0xe3, 0x09, 0x2f, 0x0b, 0xcc,
	0xb2, 0xc0, 0xd5, 0x13, 0x52, 0x6e, 0x81, 0x93, 0x13, 0x43, 0xd2, 0xdd, 0x41, 0xee, 0xd0, 0x43,
	0x44, 0x04, 0xac, 0x3c, 0xcf, 0xbc, 0x2c, 0xb9, 0x37, 0x62, 0x80, 0xc5, 0xed, 0xd5, 0x0c, 0xbd,
	0x96, 0x59, 0xbc, 0x37, 0xab, 0x26, 0xd0, 0x02, 0x4b, 0xf7, 0xb1, 0xef, 0xb3, 0x0c, 0x31, 0xca,
	0xf3, 0xc7, 0xa2, 0x7c, 0x91, 0x3b, 0x89, 0x49, 0xbf, 0x0b, 0x0a, 0x21, 0xea, 0x3b, 0xd8, 0x9f,
	0xd2, 0xbe, 0xf8, 0xd6, 0x69, 0x5f, 0x9a, 0x46, 0x60, 0xc4, 0xd7, 0x41, 0x9c, 0x75, 0x9b, 0x76,
	0xba, 0xb8, 0xc4, 0xc2, 0x49, 0x4a, 0x3c, 0x06, 0x94, 0xc9, 0x18, 0x50, 0xda, 0x93, 0x31, 0xa0,
	0xe6, 0x68, 0xbc, 0x87, 0xcf, 0xca, 0x82, 0xb9, 0xc0, 0x70, 0x74, 0x07, 0xd6, 0xc0, 0x02, 0xf2,
	0x5d, 0xe6, 0x82, 0x88, 0x05, 0x46, 0xf0, 0xeb, 0xf9, 0xc8, 0x21, 0xdf, 0x65, 0x7a, 0x78, 0x05,
	0x64, 0x49, 0xe4, 0x44, 0x43, 0x22, 0x2e, 0xb3, 0xee, 0xfb, 0xe0, 0x15, 0xdd, 0x67, 0x31, 0x63,
	0x93, 0x83, 0x2e, 0x17, 0x1f, 0x3c, 0x2a, 0xa7, 0x7e, 0xfb, 0xe5, 0x5c, 0x8e, 0x6f, 0x1b, 0x95,
	0x1e, 0x38, 0xd9, 0xc0, 0xbb, 0xc8, 0x65, 0xcc, 0x4e, 0x3a, 0x7e, 0x0b, 0x2c, 0x52, 0x0a, 0x6d,
	0xde, 0x9b, 0xac, 0xf7, 0xf3, 0x2f, 0xef, 0xf4, 0xc4, 0xb0, 0x50, 0x33, 0x4f, 0x9e, 0x96, 0x05,
	0x33, 0xdf, 0xd9, 0x57, 0x5d, 0xce, 0xd0, 0xa0, 0x95, 0x1f, 0xd3, 0xa0, 0xa0, 0xfb, 0x3d, 0x0f,
	0x93, 0x9d, 0xff, 0x25, 0x0c, 0x2d, 0xe3, 0xbe, 0xb3, 0x8b, 0xfb, 0xc3, 0xbe, 0xdd, 0xc1, 0x2e,
	0x2f, 0xb7, 0xf4, 0xb1, 0xca, 0x6d, 0x99, 0x3b, 0x52, 0x71, 0xcc, 0x0b, 0x94, 0x40, 0x6e, 0x32,
	0x2e, 0xd9, 0xdc, 0x5a, 0x32, 0xa7, 0x32, 0x9d, 0x29, 0xf1, 0xda, 0x0e, 0x9d, 0x08, 0xc5, 0xc3,
	0xea, 0xcd, 0x67, 0x4a, 0xec, 0xc2, 0x74, 0x22, 0xc4, 0xf9, 0xfa, 0x4e, 0x00, 0xcb, 0x07, 0xba,
	0x0c, 0x5e, 0x05, 0x8b, 0x21, 0xf2, 0x10, 0xe5, 0x8c, 0xd5, 0xa1, 0xf0, 0x06, 0x75, 0x98, 0xe7,
	0x48, 0x56, 0x89, 0x0d, 0x90, 0xbd, 0x8f, 0x70, 0x6f, 0x27, 0x3a, 0x26, 0x41, 0x1c, 0x5d, 0xf9,
	0x1c, 0x2c, 0xf1, 0x33, 0x7e, 0x3a, 0x44, 0x43, 0x44, 0xa0, 0x0a, 0xb2, 0x77, 0xd9, 0x8a, 0xbf,
	0x6f, 0xef, 0xbf, 0x62, 0x80, 0x30, 0x18, 0x9f, 0x1e, 0x1c, 0x19, 0xbf, 0x44, 0x5f, 0xfd, 0x29,
	0x0b, 0x95, 0xaf, 0xd3, 0x60, 0x31, 0x69, 0x08, 0x4f, 0x4f, 0x5f, 0x10, 0x7b, 0xfa, 0x24, 0x2d,
	0x70, 0x8d, 0xe1, 0x1e, 0x78, 0x60, 0xd2, 0x87, 0x1e, 0x98, 0x3b, 0x20, 0x9f, 0x18, 0x9f, 0x2c,
	0x93, 0x6f, 0x77, 0x6a, 0x80, 0xfd, 0x21, 0x7c, 0x28, 0x59, 0x99, 0x63, 0x26, 0xab, 0xf2, 0x73,
	0x1a, 0xcc, 0xa9, 0xd8, 0x7d, 0xd5, 0xe5, 0x25, 0x90, 0x23, 0xe8, 0xee, 0x10, 0xf9, 0xbc, 0xec,
	0x33, 0xe6, 0x54, 0x86, 0xab, 0x20, 0xdb, 0xc1, 0xae, 0x3b, 0x7d, 0x75, 0xb9, 0x04, 0x35, 0x30,
	0x1f, 0xf7, 0xc9, 0xf1, 0xaa, 0x36, 0x06, 0xc3, 0x2f, 0x40, 0x86, 0xf1, 0x39, 0xff, 0xd6, 0xf9,
	0x64, 0x7e, 0xe9, 0xe9, 0x77, 0xe2, 0x6a, 0xcd, 0xb2, 0x7b, 0x71, 0x89, 0x75, 0xa5, 0x87, 0x7b,
	0xb8, 0xe3, 0x21, 0xf6, 0xf0, 0xe6, 0xcc, 0xa9, 0x7c, 0xf6, 0x27, 0x01, 0xe4, 0x13, 0x5f, 0x20,
	0x70, 0x03, 0x88, 0xb5, 0xed, 0x7a, 0xdb, 0xb8, 0xde, 0xb4, 0xdb, 0x37, 0x5b, 0xba, 0xbd, 0xdd,
	0xb4, 0x5a, 0x7a, 0xdd, 0x68, 0x18, 0xba, 0x56, 0x4c, 0x49, 0x70, 0x34, 0x96, 0x0b, 0x09, 0xf3,
	0x26, 0xf6, 0xe0, 0xa5, 0x03, 0x88, 0x86, 0xf1, 0x99, 0xae, 0xd9, 0x2d, 0xd3, 0xa8, 0xeb, 0x45,
	0x41, 0x5a, 0x1b, 0x8d, 0xe5, 0x53, 0x09, 0xc4, 0xfe, 0x10, 0xa5, 0x9f, 0x31, 0x33, 0x40, 0xbd,
	0x79, 0x75, 0xcb, 0xb0, 0xae, 0x15, 0xd3, 0xd2, 0xea, 0x68, 0x2c, 0xc3, 0x04, 0x88, 0xcf, 0x43,
	0x29, 0xf3, 0xe0, 0xfb, 0x52, 0xea, 0xec, 0xb7, 0x73, 0x60, 0x69, 0x66, 0x6c, 0xc3, 0x8b, 0x40,
	0x9a, 0x78, 0xb2, 0xda, 0xb5, 0xf6, 0xb6, 0x75, 0xe0, 0xd8, 0x2b, 0xa3, 0xb1, 0x5c, 0x9c, 0x81,
	0xd0, 0x83, 0x5f, 0x04, 0xab, 0x07, 0x50, 0x56, 0xbb, 0xd6, 0xd4, 0xd4, 0x9b, 0x45, 0x41, 0x12,
	0x47, 0x63, 0x79, 0x65, 0x06, 0x61, 0x45, 0x8e, 0xef, 0xaa, 0x7b, 0x47, 0xa3, 0xcc, 0xb6, 0xae,
	0x15, 0xd3, 0x47, 0xa3, 0xc2, 0x08, 0xb9, 0x47, 0xa0, 0x6e, 0xe8, 0x56, 0xdb, 0x68, 0x5e, 0x2d,
	0xce, 0x1d, 0x81, 0xe2, 0xbd, 0x0c, 0xaf, 0x1c, 0xba, 0x97, 0x66, 0x58, 0x6d, 0xd3, 0x50, 0xb7,
	0x69, 0xbc, 0x8c, 0x74, 0x7a, 0x34, 0x96, 0xd7, 0x66, 0x90, 0x1a, 0x26, 0x51, 0x88, 0x3b, 0x43,
	0x06, 0xff, 0x18, 0xbc, 0x7b, 0x00, 0xde, 0x30, 0x9a, 0x86, 0x75, 0x4d, 0xd7, 0x8a, 0xf3, 0x33,
	0x89, 0x89, 0xb1, 0x0d, 0xec, 0x63, 0xb2, 0x83, 0x5c, 0xf8, 0xc9, 0x7e, 0x46, 0x39, 0xae, 0x5e,
	0x6b, 0xd6, 0xf5, 0xad, 0x2d, 0x5d, 0x2b, 0x66, 0x25, 0x69, 0x34, 0x96, 0x57, 0x67, 0x80, 0x75,
	0xc7, 0xef, 0x22, 0xcf, 0x43, 0x2e, 0x4f, 0xd0, 0x1e, 0xc8, 0xf3, 0x6f, 0x26, 0x56, 0x52, 0xe7,
	0xc1, 0xa9, 0x9a, 0xa6, 0x99, 0xba, 0x65, 0xc5, 0x79, 0xbe, 0xb0, 0x69, 0xab, 0x37, 0xdb, 0xba,
	0x55, 0x4c, 0xf1, 0x44, 0xef, 0xdb, 0x5e, 0xd8, 0x54, 0xf7, 0x22, 0x44, 0x0e, 0x41, 0x36, 0x37,
	0x38, 0x44, 0x38, 0x04, 0xd9, 0xdc, 0x60, 0x90, 0x38, 0xb4, 0x7a, 0xfd, 0xf1, 0xf3, 0x92, 0xf0,
	0xe4, 0x79, 0x49, 0xf8, 0xeb, 0x79, 0x49, 0x78, 0xf8, 0xa2, 0x94, 0x7a, 0xf2, 0xa2, 0x94, 0xfa,
	0xfd, 0x45, 0x29, 0x75, 0xeb, 0xa3, 0x44, 0x2f, 0xed, 0xcf, 0xda, 0xe4, 0xbf, 0xa3, 0xea, 0xee,
	0x8c, 0xc4, 0xda, 0xab, 0x93, 0x65, 0xf3, 0xe7, 0xc2, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0x93, 0x4a, 0x57, 0x53, 0x0d, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AuctionCreationFee) != len(that1.AuctionCreationFee) {
		return false
	}
	for i := range this.AuctionCreationFee {
		if !this.AuctionCreationFee[i].Equal(&that1.AuctionCreationFee[i]) {
			return false
		}
	}
	if this.ExtendedPeriod != that1.ExtendedPeriod {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExtendedPeriod != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.ExtendedPeriod))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AuctionCreationFee) > 0 {
		for iNdEx := len(m.AuctionCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuctionCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFundraising(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BaseAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x78
	}
	if len(m.EndTimes) > 0 {
		for iNdEx := len(m.EndTimes) - 1; iNdEx >= 0; iNdEx-- {
			n, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTimes[iNdEx], dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTimes[iNdEx]):])
			if err != nil {
				return 0, err
			}
			i -= n
			i = encodeVarintFundraising(dAtA, i, uint64(n))
			i--
			dAtA[i] = 0x72
		}
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintFundraising(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.RemainingCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size := m.WinningPrice.Size()
		i -= size
		if _, err := m.WinningPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if len(m.VestingSchedules) > 0 {
		for iNdEx := len(m.VestingSchedules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingSchedules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFundraising(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.VestingAddress) > 0 {
		i -= len(m.VestingAddress)
		copy(dAtA[i:], m.VestingAddress)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.VestingAddress)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PayingCoinDenom) > 0 {
		i -= len(m.PayingCoinDenom)
		copy(dAtA[i:], m.PayingCoinDenom)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.PayingCoinDenom)))
		i--
		dAtA[i] = 0x42
	}
	{
		size, err := m.SellingCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.StartPrice.Size()
		i -= size
		if _, err := m.StartPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.PayingPoolAddress) > 0 {
		i -= len(m.PayingPoolAddress)
		copy(dAtA[i:], m.PayingPoolAddress)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.PayingPoolAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SellingPoolAddress) > 0 {
		i -= len(m.SellingPoolAddress)
		copy(dAtA[i:], m.SellingPoolAddress)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.SellingPoolAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Auctioneer) > 0 {
		i -= len(m.Auctioneer)
		copy(dAtA[i:], m.Auctioneer)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.Auctioneer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FixedPriceAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FixedPriceAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FixedPriceAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BaseAuction != nil {
		{
			size, err := m.BaseAuction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFundraising(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnglishAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnglishAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnglishAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExtendRate.Size()
		i -= size
		if _, err := m.ExtendRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Extended != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Extended))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.MaximumBidPrice.Size()
		i -= size
		if _, err := m.MaximumBidPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BaseAuction != nil {
		{
			size, err := m.BaseAuction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFundraising(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VestingSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ReleaseTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.ReleaseTime):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintFundraising(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VestingQueues) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingQueues) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingQueues) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Queues) > 0 {
		for iNdEx := len(m.Queues) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Queues[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFundraising(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *VestingQueue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingQueue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingQueue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ReleaseTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.ReleaseTime):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintFundraising(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x22
	{
		size, err := m.PayingCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Auctioneer) > 0 {
		i -= len(m.Auctioneer)
		copy(dAtA[i:], m.Auctioneer)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.Auctioneer)))
		i--
		dAtA[i] = 0x12
	}
	if m.AuctionId != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Bid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Eligible {
		i--
		if m.Eligible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Height != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFundraising(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintFundraising(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Sequence != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if m.AuctionId != 0 {
		i = encodeVarintFundraising(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFundraising(dAtA []byte, offset int, v uint64) int {
	offset -= sovFundraising(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuctionCreationFee) > 0 {
		for _, e := range m.AuctionCreationFee {
			l = e.Size()
			n += 1 + l + sovFundraising(uint64(l))
		}
	}
	if m.ExtendedPeriod != 0 {
		n += 1 + sovFundraising(uint64(m.ExtendedPeriod))
	}
	return n
}

func (m *BaseAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFundraising(uint64(m.Id))
	}
	if m.Type != 0 {
		n += 1 + sovFundraising(uint64(m.Type))
	}
	l = len(m.Auctioneer)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = len(m.SellingPoolAddress)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = len(m.PayingPoolAddress)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = m.StartPrice.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = m.SellingCoin.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = len(m.PayingCoinDenom)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = len(m.VestingAddress)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	if len(m.VestingSchedules) > 0 {
		for _, e := range m.VestingSchedules {
			l = e.Size()
			n += 1 + l + sovFundraising(uint64(l))
		}
	}
	l = m.WinningPrice.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = m.RemainingCoin.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovFundraising(uint64(l))
	if len(m.EndTimes) > 0 {
		for _, e := range m.EndTimes {
			l = github_com_gogo_protobuf_types.SizeOfStdTime(e)
			n += 1 + l + sovFundraising(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovFundraising(uint64(m.Status))
	}
	return n
}

func (m *FixedPriceAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAuction != nil {
		l = m.BaseAuction.Size()
		n += 1 + l + sovFundraising(uint64(l))
	}
	return n
}

func (m *EnglishAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAuction != nil {
		l = m.BaseAuction.Size()
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = m.MaximumBidPrice.Size()
	n += 1 + l + sovFundraising(uint64(l))
	if m.Extended != 0 {
		n += 1 + sovFundraising(uint64(m.Extended))
	}
	l = m.ExtendRate.Size()
	n += 1 + l + sovFundraising(uint64(l))
	return n
}

func (m *VestingSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ReleaseTime)
	n += 1 + l + sovFundraising(uint64(l))
	l = m.Weight.Size()
	n += 1 + l + sovFundraising(uint64(l))
	return n
}

func (m *VestingQueues) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Queues) > 0 {
		for _, e := range m.Queues {
			l = e.Size()
			n += 1 + l + sovFundraising(uint64(l))
		}
	}
	return n
}

func (m *VestingQueue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovFundraising(uint64(m.AuctionId))
	}
	l = len(m.Auctioneer)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = m.PayingCoin.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ReleaseTime)
	n += 1 + l + sovFundraising(uint64(l))
	return n
}

func (m *Bid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovFundraising(uint64(m.AuctionId))
	}
	if m.Sequence != 0 {
		n += 1 + sovFundraising(uint64(m.Sequence))
	}
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovFundraising(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovFundraising(uint64(l))
	l = m.Coin.Size()
	n += 1 + l + sovFundraising(uint64(l))
	if m.Height != 0 {
		n += 1 + sovFundraising(uint64(m.Height))
	}
	if m.Eligible {
		n += 2
	}
	return n
}

func sovFundraising(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFundraising(x uint64) (n int) {
	return sovFundraising(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *VestingQueues) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForQueues := "[]VestingQueue{"
	for _, f := range this.Queues {
		repeatedStringForQueues += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForQueues += "}"
	s := strings.Join([]string{`&VestingQueues{`,
		`Queues:` + repeatedStringForQueues + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFundraising(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionCreationFee = append(m.AuctionCreationFee, types.Coin{})
			if err := m.AuctionCreationFee[len(m.AuctionCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedPeriod", wireType)
			}
			m.ExtendedPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExtendedPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BaseAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= AuctionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auctioneer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auctioneer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellingPoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellingPoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayingPoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayingPoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StartPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellingCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellingCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingSchedules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingSchedules = append(m.VestingSchedules, VestingSchedule{})
			if err := m.VestingSchedules[len(m.VestingSchedules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinningPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WinningPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndTimes = append(m.EndTimes, time.Time{})
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&(m.EndTimes[len(m.EndTimes)-1]), dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AuctionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FixedPriceAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedPriceAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedPriceAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAuction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAuction == nil {
				m.BaseAuction = &BaseAuction{}
			}
			if err := m.BaseAuction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnglishAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnglishAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnglishAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAuction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAuction == nil {
				m.BaseAuction = &BaseAuction{}
			}
			if err := m.BaseAuction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumBidPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaximumBidPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extended", wireType)
			}
			m.Extended = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Extended |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExtendRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ReleaseTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingQueues) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingQueues: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingQueues: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Queues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Queues = append(m.Queues, VestingQueue{})
			if err := m.Queues[len(m.Queues)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingQueue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingQueue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingQueue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auctioneer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auctioneer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayingCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PayingCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ReleaseTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Bid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFundraising
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFundraising
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eligible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Eligible = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFundraising(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFundraising
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFundraising(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFundraising
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFundraising
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFundraising
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFundraising
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFundraising
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFundraising        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFundraising          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFundraising = fmt.Errorf("proto: unexpected end of group")
)
