name: Check Markdown links

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '* */24 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          folder-path: "."
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/linkchecker-config.json'
