name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed
on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum
      - name: Display go version
        run: go version
      - run: make build

  install-runsim:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum
      - name: Display go version
        run: go version
      - name: Install runsim
        run: export GO111MODULE="on" && go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v2
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: [ build, install-runsim ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: test-sim-nondeterminism
        run: |
          make test-sim-nondeterminism
        if: env.GIT_DIFF

  test-sim-import-export:
    runs-on: ubuntu-latest
    needs: [ build, install-runsim ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6
        with:
          SUFFIX_FILTER: |
            **/**.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-import-export
        run: |
          make test-sim-import-export
        if: env.GIT_DIFF

  test-sim-after-import:
    runs-on: ubuntu-latest
    needs: [ build, install-runsim ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6
        with:
          SUFFIX_FILTER: |
            **/**.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-after-import
        run: |
          make test-sim-after-import
        if: env.GIT_DIFF
