name: Unit Tests

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum

      - name: Run unit tests
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... $(go list ./...)

      - name: filter non-testable files
        run: |
          excludelist="$(find ./ -type f -name '*.go' | xargs grep -l 'DONTCOVER')"
          excludelist+=" $(find ./ -type f -name '*.pb.go')"
          excludelist+=" $(find ./ -type f -name '*.pb.gw.go')"
          excludelist+=" $(find ./app -type d)"
          excludelist+=" $(find ./cmd -type d)"
          excludelist+=" $(find ./proto -type d)"
          excludelist+=" $(find ./testutil -type d)"
          excludelist+=" $(find ./tools -type d)"
          for filename in ${excludelist}; do
            filename=${filename#".//"}
            echo "Excluding ${filename} from coverage report..."
            filename=$(echo "$filename" | sed 's/\//\\\//g')
            sed -i.bak "/""$filename""/d" coverage.txt
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
          verbose: true
